### ISSUE TITLE
Url redirect

### ISSUE THREAD

**Issue by Alex-Maitland** [gigapipehq/gigapipe.io#15]
Since the website change the terms and the privacy policy linked by the Gigapipe apps no longer go to the policies.

They're now under a combined one. So can the following please be redirected to:

From:
https://gigapipe.com/privacy-policy/ 
https://gigapipe.com/terms/  

Redirected to: https://gigapipe.com/legal/

Thanks. We can update the UIs but we'll do it with other changes so as to avoid an unnecessary redeployment.

Alex

**Comment by lmangani** [comment]
Implemented. You can add more by extending [this](https://github.com/gigapipehq/gigapipe.io/blob/main/rspress.config.ts#L28) array of rules.
